- name: Install contained // infra/ansible/playbook/packages/containerd/install.yaml
  hosts:
    - prod
    - test
    - dev
  become: true

  tasks:
    - name: Is containerd installed
      ansible.builtin.command: which containerd
      changed_when: false
      ignore_errors: true
      register: check_containerd

    - name: Adding a containerd repository
      ansible.builtin.copy:
        src: ./docker-ce.repo.j2
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: "644"
        remote_src: false
      when: check_containerd.rc != 0

    - name: Install containerd
      ansible.builtin.dnf:
        name: containerd.io
        state: present
      when: check_containerd.rc != 0

    - name: Generate and apply a default containerd configuration
      ansible.builtin.command: containerd config default | sudo tee /etc/containerd/config.toml
      changed_when: false
      when: check_containerd.rc != 0

    - name: Launching containerd service
      ansible.builtin.systemd_service:
        name: containerd
        state: restarted
        enabled: true
      when: check_containerd.rc != 0
