---
- name: Installing CRI-O // infra/ansible/playbook/packages/cri/cri-o/install.yaml
  hosts:
    - dev
    - test
    - prod
  become: true
  tasks:
    - name: Adding a CRI-O repository
      ansible.builtin.copy:
        src: ./cri-o.repo.j2
        dest: /etc/yum.repos.d/cri-o.repo
        remote_src: false

    - name: Install CRI-O
      ansible.builtin.dnf:
        name: cri-o
        state: latest

    - name: Launching CRI-O service
      ansible.builtin.systemd_service:
        name: crio
        state: started
        enabled: true
