---
- name: Updating the system and restarting it // infra/ansible/playbook/start/install.yaml
  hosts:
    - dev
    - test
    - prod
  become: true
  tasks:
    - name: Perform a DNF system update
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true

    - name: Reboot system
      ansible.builtin.reboot:
        reboot_timeout: 300
