global:
  domain: argocd.lune.su

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: "root"
    tls: true
    extraHosts:
      - name: argocd-alias.lune.su
        path: /
