apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: bootstrap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/MounTemed/ephemera'
    targetRevision: main
    path: kubernetes/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
