- name: Complete installation of ArgoCD
  hosts: unstable
  become: true 
  vars:
    manifest_url: "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"
    manifest_path: "/home/user/download/install.yaml"
  vars_files:
    -  ../../secrets/secrets.yaml

  tasks:
    - name: Ensure download directory exists
      ansible.builtin.file:
        path: /home/user/download
        state: directory
        mode: "0755"

    - name: Download Argo CD manifest to the cluster
      ansible.builtin.get_url:
        url: "{{ manifest_url }}"
        dest: "{{ manifest_path }}"
        mode: "0644"

    - name: Create a namespace argocd
      kubernetes.core.k8s:
        name: argocd
        api_version: v1
        kind: Namespace
        state: present
    
    - name: Add to argocd namespace docker hub secret
      ansible.builtin.shell: |
        kubectl create secret docker-registry docker-hub-secret \
          --docker-username={{ docker_login }} \
          --docker-password={{ docker_password }} \
          -n argocd \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Apply Argo CD manifest to the cluster
      kubernetes.core.k8s:
        state: present
        src: "{{ manifest_path }}"
        namespace: argocd

    - name: Copy our config from host to vpc
      ansible.builtin.copy:
        src: ./argo-config.yaml
        dest: /home/user/argo-config.yaml
        remote_src: false

    - name: We use our argocd-config.yaml
      kubernetes.core.k8s: 
        state: present
        src: /home/user/argo-config.yaml
        namespace: argocd
