include:
  # fmt
  - pipeline/code/ansible.yaml
  - pipeline/code/golang.yaml
  - pipeline/code/kubernetes.yaml

  #docker
  - pipeline/docker/build.yaml
  - pipeline/docker/push.yaml

  #sast
  - pipeline/security/ansible.yaml
  - pipeline/security/docker.yaml
  - pipeline/security/golang.yaml
  - pipeline/security/kubernetes.yaml

  #ansible
  - pipeline/ansible/check.yaml

  #notify
  - pipeline/notify/msg.yaml

stages:
  # code
  - code-ansible-yamllint
  - code-ansible-lint
  - code-gofmt
  - code-kubelinter
  - code-kubeconfrom
  - code-helm-lint
  - code-helm-template
  - code-helm-chart-testing
  - code-kubernetes-yamllint

  # docker
  - ci-pull-request
  - ci-deploy

  #sast
  - ansible-checkov
  - ansible-kics
  - golang-gosec
  - docker-trivy
  - docker-snyk
  - docker-grype
  - docker-anchore
  - k8s-checkov
  - k8s-kics

  # ansible
  - ansible-deploy-test

  # notify
  - gitlab-msg
