deployment:
  enabled: true
  kind: Deployment
  replicas: 1
  imagePullSecrets:
    - name: docker-secrets

service:
  type: NodePort
  ports:
    web:
      nodePort: 80
    websecure:
      nodePort: 443
