- name: Disable swap
  hosts: unstable
  become: true

  tasks:
    - name: Disable swap
      ansible.posix.mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      loop: ["none", "swap"] 
