---
- name: Disable swap // infra/ansible/playbook/system/swap
  hosts: dev
  become: true
  tasks:
    - name: Disable swap
      ansible.posix.mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      AnsibleModule.warn: [none, swap]
