---
- name: Installing tar // infra/ansible/playbook/packages/unpackers/tar.yaml
  hosts:
    - dev
    - test
    - prod
  become: true
  tasks:
    - name: Install tar
      ansible.builtin.dnf:
        name: tar
        state: latest
