hostNetwork: true
ports:
  web:
    port: 80
  websecure:
    port: 443

entryPoints:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          port: 443

deployment:
  enable: true
  imagePullSecrets:
    - name: docker-secrets

ingressClass:
  enabled: false

securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

tls:
  stores:
    default:
      defaultCertificate:
        enabled: false

gateway:
  enabled: false

logs:
  general:
    level: INFO
  access:
    enabled: true

metrics:
  prometheus:
    enabled: true
