hostNetwork: true
ports:
  web:
    port: 80
  # websecure:
  #   port: 443

deployment:
  enable: true
  imagePullSecrets:
    - name: docker-secrets

ingressClass:
  enabled: false

securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

gateway:
  enabled: true
  listeners:
    web:
      port: 80
      protocol: HTTP
      namespacePolicy:
        from: All
    # websecure:
    #   port: 443
    #   protocol: HTTPS
    #   namespacePolicy:
    #     from: All

logs:
  general:
    level: INFO
  access:
    enabled: true

metrics:
  prometheus:
    enabled: true
