ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`dashboard.lune.su`) || PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    entryPoints: ["traefik"]

hostNetwork: true

ports:
  web:
    port: 80
  websecure:
    port: 443

deployment:
  imagePullSecrets:
    - name: docker-secrets

ingressClass:
  enabled: false

providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

gateway:
  enabled: true
  listeners:
    web:
      port: 80
      protocol: HTTP
      namespacePolicy:
        from: All

    websecure:
      hostname: "*.lune.su"
      port: 443
      protocol: HTTPS
      namespacePolicy:
        from: All
      mode: Terminate
      tls:
        certificateRefs:
          - name: lune-su-tls

logs:
  general:
    level: INFO
  access:
    enabled: true

metrics:
  prometheus:
    enabled: true
