- name: Installing istio // infra/ansible/playbook/kubernetes/helm/istio/install.yaml
  hosts: dev
  become: true
  tasks:
    - name: Add istio chart repository to Helm
      kubernetes.core.helm_repository:
        name: istio-base
        repo_url: https://istio-release.storage.googleapis.com/charts

    - name: Copy the required values.yaml
      ansible.builtin.copy:
        src: ../../../../../../kubernetes/settings/argocd/values.yaml
        dest: /home/user/argo.yaml
        remote_src: false

    - name: Install istio
      kubernetes.core.helm:
        name: istio-base
        chart_ref: istio/base
        release_namespace: nm-istio

    - name: Delete the file that is no longer needed
      ansible.builtin.file:
        path: /home/user/argo.yaml
        state: absent
