include:
  # fmt
  - pipeline/code/ansible.yaml
  - pipeline/code/golang.yaml
  - pipeline/code/kubernetes.yaml

  #docker
  - pipeline/docker/build.yaml
  - pipeline/docker/push.yaml

  #sast
  - pipeline/security/ansible.yaml
  - pipeline/security/docker.yaml
  - pipeline/security/golang.yaml
  - pipeline/security/kubernetes.yaml

  #ansible
  - pipeline/ansible/check.yaml

  #notify
  - pipeline/notify/msg.yaml

stages:
  # code
  - code-yamllint
  - code-ansible-lint
  - code-gofmt
  - code-kubelinter
  - code-kubeconfrom
  - code-kubeval
  - code-kubectl-validate
  - code-helm-Lint
  - code-helm-chart-testing
  - code-helm-template

  # docker
  - build
  - push

  #sast
  - ansible-checkov
  - ansible-kics
  - ansible-steampunk-spotter
  - ansible-semgrep
  - golang-semgrep
  - golang-sonarqube
  - golang-gosec
  - docker-trivy
  - docker-snyk
  - docker-clair
  - docker-grype
  - docker-anchore
  - k8s-checkov
  - k8s-kubelinter
  - k8s-kubespace
  - k8s-kics
  - k8s-trivy

  # ansible
  - ansible-molecule

  # notify
  - gitlab-msg
