apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: prometheus-traefik-gateway
  namespace: nm-traefik
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: websecure
      port: 443
      protocol: HTTPS
      hostname: "prometheus.lune.su"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: prometheus-lune-tls
            kind: Secret
            group: ""
