trivy:
  stage: sast
  image:
    name: docker.io/aquasec/trivy:latest
  dependencies:
    name: creating-image
  script:
    - trivy image "$CI_REGISTRY_IMAGE:testing-$CI_COMMIT_SHORT_SHA"

checkov:
  stage: sast
  allow_failure: true
  image:
    name: bridgecrew/checkov:latest
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  rules:
    - if: $SAST_DISABLED
      when: never
    - if: $CI_COMMIT_BRANCH
      exists:
        - "**/*.yml"
        - "**/*.yaml"
        - "**/*.tf"
  script:
    - checkov -d . -o junitxml | tee checkov.test.xml
  artifacts:
    reports:
      junit: "checkov.test.xml"
    paths:
      - "checkov.test.xml"

kics:
  stage: sast
  image:
    name: docker.io/checkmarx/kics:latest
  script:
    - kics scan -p ./image/app/Conatinerfile

semgrep:
  stage: sast
  image:
    name: docker.io/semgrep/semgrep:latest
  script:
    - semgrep ci

clair:
  stage: dast
  script:
    - ssh root@$IVP4 "dnf install -y clair"
    - ssh # хз как но надо забрать kubeclair/config.yaml

grype:
  stage: dast
  script:
    - ssh root@$IPV4 "curl -sSfL https://get.anchore.io/grype | sudo sh -s -- -b /usr/local/bin"

snyk:
  stage: dast
  script:
    - ssh root@$IPV4 "dnf install -y snyk"
    - ssh root@$IPV4 "snyk monitor &"

kubespace:
  stage: dast
  script:
    - ssh root@$IPV4 "curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash"

kube-bench:
  stage: dast
