trivy:
  stage: sast
  image:
    name: docker.io/aquasec/trivy:latest
  dependencies:
    name: creating-image
  script:
    - trivy image "$CI_REGISTRY_IMAGE:testing-$CI_COMMIT_SHORT_SHA"

checkov:
  stage: sast
  allow_failure: true
  image:
    name: bridgecrew/checkov:latest
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  rules:
    - if: $SAST_DISABLED
      when: never
    - if: $CI_COMMIT_BRANCH
      exists:
        - "**/*.yml"
        - "**/*.yaml"
        - "**/*.tf"
  script:
    - checkov -d . -o junitxml | tee checkov.test.xml
  artifacts:
    reports:
      junit: "checkov.test.xml"
    paths:
      - "checkov.test.xml"

kics:
  stage: sast
  image:
    name: docker.io/checkmarx/kics:latest
  script:
    - kics scan -p ./image/app/Conatinerfile

terrascan:
  stage: sast
  image:
    name: docker.io/tenable/terrascan:latest
  script:
    - cd ./infra/terraform && terrascan --init && terrascan scan ./ --find-vuln

semgrep:
  stage: sast
  image:
    name: docker.io/semgrep/semgrep:latest
  script:
    - semgrep ci

clair:
  stage: dast

grype:
  stage: dast

snyk:
  stage: dast

kubespace:
  stage: dast

kube-bench:
  stage: dast

cilium-hubble:
  stage: dast
