---
- name: Installing elk in a cluster
  hosts: dev
  become: true
  tasks:
    - name: Add elk chart repository to Helm
      kubernetes.core.helm_repository:
        name: elastic
        repo_url: https://helm.elastic.co

    - name: Install elk/elasticsearch
      kubernetes.core.helm:
        name: elk-elasticsearch
        chart_ref: elastic/elasticsearch
        release_namespace: nm-elk
        create_namespace: true
        wait: true
