---
- name: Installing Grafana
  ansible.builtin.import_playbook: ./grafana.yaml

- name: Installing prometheus
  ansible.builtin.import_playbook: ./prometheus-comm.yaml

- name: Installing alloy
  ansible.builtin.import_playbook: ./alloy.yaml
