---
- name: Installing node-exporter in a cluster
  hosts: unstable
  become: true
  tasks:
    - name: Add node-exporter chart repository to Helm
      kubernetes.core.helm_repository:
        name: node-exporter
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Install node-exporter
      kubernetes.core.helm:
        name: node-exporter
        chart_ref: node-exporter/node-exporter
        release_namespace: nm-monitoring
        wait: true
