- name: Creating a StorageClass
  ansible.builtin.import_playbook: ./storage.yaml

- name: Creating a PersistentVolumeClaim
  ansible.builtin.import_playbook: ./pvc.yaml

- name: Creating a PersistentVolume
  ansible.builtin.import_playbook: ./pv.yaml
