---
- name: Creating PVCs // infra/ansible/playbook/kubernetes/default/storage/pvc.yaml
  hosts: dev
  become: true
  tasks:
    - name: PersistentVolumeClaim for gitlab
      kubernetes.core.k8s:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: nm-gitlab
        name: gitlab-pvc
        state: present
        resource_definition:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: local-path

    - name: PersistentVolumeClaim for elk
      kubernetes.core.k8s:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: nm-elk
        name: elk-pvc
        state: present
        resource_definition:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: local-path

    - name: PersistentVolumeClaim for nexus
      kubernetes.core.k8s:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: nm-nexus
        name: nexus-pvc
        state: present
        resource_definition:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: local-path

    - name: PersistentVolumeClaim for prometheus
      kubernetes.core.k8s:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: nm-monitoring
        name: prometheus-pvc
        state: present
        resource_definition:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: local-path
