---
- name: Create docker-registry secrets // infra/ansible/playbook/kubernetes/default/secrets/docker.yaml
  hosts: masters
  become: true
  vars:
    docker_registry_username: "{{ docker_login }}"
    docker_registry_password: "{{ docker_password }}"
    namespaces:
      - nm-argo
      - nm-gitlab
      - nm-monitoring
      - nm-nexus
      - nm-traefik
      - nm-cert-manager
      - nm-app
      - nm-local-path-storage

  vars_files:
    - ../../../secrets/secrets.yaml

  tasks:
    - name: Create docker-registry secret in each namespace
      ansible.builtin.shell: |
        set -o pipefail
        kubectl create secret docker-registry docker-secrets \
          --docker-username={{ docker_login }} \
          --docker-password={{ docker_password }} \
          -n {{ item }} --dry-run=client -o yaml | kubectl apply -f -
      loop: "{{ namespaces }}"
      loop_control:
        label: "{{ item }}"
      changed_when: false
      no_log: true
