---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm
  namespace: nm-argo
spec:
  project: default
  source:
    repoURL: https://github.com/MounTemed/Ephemera
    targetRevision: main
    path: kubernetes/settings/helm/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base
  namespace: nm-argo
spec:
  project: default
  source:
    repoURL: https://github.com/MounTemed/Ephemera
    targetRevision: main
    path: kubernetes/settings/base/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: nm-argo
spec:
  project: default
  source:
    repoURL: https://github.com/MounTemed/Ephemera
    targetRevision: main
    path: kubernetes/apps/ephemera
    helm:
      releaseName: ephemera
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
