---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm
  namespace: nm-argo
spec:
  project: default
  source:
    repoURL: https://github.com/MounTemed/Ephemera
    targetRevision: main
    path: kubernetes/helm/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      allowEmpty: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base
  namespace: nm-argo
spec:
  project: default
  source:
    repoURL: https://github.com/MounTemed/Ephemera
    targetRevision: main
    path: kubernetes/base/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      allowEmpty: true
      selfHeal: true
