global:
  image:
    PullSecrets:
      - name: docker-secrets

image:
  registry: docker.io
  repository: grafana/grafana
  pullPolicy: IfNotPresent

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server:80
        access: proxy
        isDefault: true
