FROM golang:1.25.0-bookworm AS builder

WORKDIR /app

COPY main.go .

RUN CGO_ENABLED=0 go build -o server ./main.go
RUN useradd -u 1000 -s /bin/sh const

FROM scratch

WORKDIR /app

COPY --from=builder /app/server /app/server
COPY --from=builder /etc/passwd /etc/passwd
COPY index.html /app/index.html

USER const

EXPOSE 8080

ENTRYPOINT [ "/app/server" ]
