# global:
#   enabled: true
#   imagePullSecrets:
#     - name: docker-secrets
#   tlsDisable: false
#   psp:
#     enable: true
#   serverTelemetry:
#     prometheusOperator: true
#   injector:
#     replicas: 2
#     leaderElectron:
#       enabled: true
#   image:
#     repository: "docker.io/hashicorp/vault-k8s"
#   agentImage:
#     repository: "docker.io/hashicorp/vault"
