stages:
  # BUILD DOCKER IMAGES
  - docker

  # LINT
  - lint

  # SECURITY SAST
  - sast

  # CREATE VPC
  - validate
  - create
  - env

  # PACKAGES
  - package

  # ANSIBLE
  - playbook

  # ARGOCD-APPSET
  - appset

  # TESTFULL
  - app

  # SECURITY DAST
  - dast

  # NOTIFY
  - notify

  # DELETE VPC
  - destroy

include:
  - local: "testgin/images.yml"
  - local: "testing/code_style.yml"
  - local: "testing/security_code.yml"
  - local: "testing/creating_environment.yml"
  - local: "testing/packages.yml"
  - local: "testing/installation.yml"
  - local: "testing/test_full.yml"
  - local: "testing/notify.yml"

  - component: gitlab.com/components/sast/sast@main
  - template: Jobs/SAST.gitlab-ci.yml
