apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-theme
  namespace: nm-argo
data:
  data:
    admin.enabled: "true"
    application.instanceLabelKey: argocd.argoproj.io/instance
    exec.enabled: "false"
    server.rbac.log.enforce.enable: "false"
    statusbadge.enabled: "false"
    timeout.hard.reconciliation: 0s
    timeout.reconciliation: 180s
    ui.cssurl: https://cdn.jsdelivr.net/gh/code-crusher/argocd-gravity-theme@main/argo-theme.css
    url: https://argo.lune.su
