global:
  PullSecrets:
    - name: docker-secrets
  hosts:
    domain: gitlab.lune.su
    https: true
  ingress:
    provider: traefik
    enabled: true
    path: /
    tls:
      enabled: true
      SecretName: gitlab-lune-tls
    configureCertmanager: false
  initialRootPassword:
    secret: gitlab-secret-password
    key: password
  edition: ce

gitlab-runner:
  install: false

installCertmanager: false

certmanager:
  installCRDs: false
  nameOverride: certmanager

nginx-ingress: &nginx-ingress
  enabled: false
