global:
  hosts:
    domain: lune.su
    hostname: gitlab
    https: true
  ingress:
    enabled: true
    provider: traefik
    class: traefik
    configureCertmanager: false
  initialRootPassword:
    secret: gitlab-secret-password
    key: password
  edition: ce
  minio:
    enabled: true

gitlab-runner:
  install: true
  podSecurityContext:
    seccompProfile:
      type: "RuntimeDefault"

installCertmanager: false

prometheus:
  install: false

certmanager:
  installCRDs: false
  nameOverride: certmanager

nginx-ingress: &nginx-ingress
  enabled: false
