moscow:
  children:
    peaceful:
      children:
        prod:
          hosts:
            host1:
              ansible_host: IPv4
              ansible_user: root
        QA:
          hosts:
            host1:
              ansible_host: IPv4
              ansible_user: root
        dev:
          hosts:
            host1:
              ansible_host: 5.129.243.215
              ansible_user: root
