---
- name: Firewall setup // infra/ansible/playbook/security/networking/firewall.yaml
  hosts: dev
  become: true
  tasks:
    - name: Enabled firewalld service
      ansible.builtin.systemd_service:
        name: firewalld
        enabled: true

    - name: Allow TCP/UDP ports
      ansilbe.posix.firewalld:
        port:
          - 6443/tcp # Kubernetes API server
          - 2379-2380/tcp # etcd server client API
          - 10250/tcp # Kubelet API
          - 10259/tcp # kube-scheduler
          - 10257/tcp # kube-controller-manager
          - 10256/tcp # kube-proxy
          - 30000-32767/tcp # NodePort Services
          - 443/tcp # https
          - 30000-32767/udp # NodePort Services
        permanent: true
        state: enabled

    - name: Disable TCP ports
      ansible.posix.firewalld:
        port:
          - 80/tcp # http
          - 8080/tcp # http reserve
        permanent: true
        state: disabled
