---
- name: Installing ArgoCD
  hosts: dev
  become: true

  tasks:
    - name: Add ArgoCD chart repository to Helm
      kubernetes.core.helm_repository:
        name: argo
        repo_url: https://argoproj.github.io/argo-helm

    - name: Install ArgoCD
      kubernetes.core.helm:
        name: argo
        chart_ref: argo/argo-cd
        release_namespace: nm-argo
        create_namespace: true
        values_files:
          - ../../../../../../kubernetes/argocd/values.yaml
        wait: true
