---
- name: Installing ArgoCD // infra/ansible/playbook/kubernetes/helm/argo/install.yaml
  hosts: dev
  become: true

  tasks:
    - name: Add ArgoCD chart repository to Helm
      kubernetes.core.helm_repository:
        name: argo
        repo_url: https://argoproj.github.io/argo-helm

    - name: Copy the required values.yaml
      ansible.builtin.copy:
        src: ../../../../../../kubernetes/settings/argocd/values.yaml
        dest: /home/user/argo.yaml
        remote_src: false

    - name: Install ArgoCD
      kubernetes.core.helm:
        name: argo
        chart_ref: argo/argo-cd
        release_namespace: nm-argo
        values_files:
          - /home/user/argo.yaml

    - name: Delete the file that is no longer needed
      ansible.builtin.file:
        path: /home/user/argo.yaml
        state: absent
