---
- name: Installing Nexus in a cluster
  hosts: dev
  become: true
  tasks:
    - name: Add Nexus chart repository to Helm
      kubernetes.core.helm_repository:
        name: nexus
        repo_url: https://sonatype.github.io/helm3-charts/

    - name: Copy the required values.yaml
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/kubernetes/nexus/values.yaml"
        dest: /home/user/nexus.yaml

    - name: Install Nexus
      kubernetes.core.helm:
        name: nexus
        chart_ref: nexus/nexus-repository-manager
        release_namespace: nm-nexus
        create_namespace: true
        values_files:
          - /home/user/nexus.yaml
        wait: true

    - name: Delete the file that is no longer needed
      ansible.builtin.file:
        src: /home/user/nexus.yaml
        state: absent
