---
- name: Temporarily disable firewalld // infra/ansible/playbook/system/network/firewalld.yaml
  hosts:
    - dev
    - test
    - prod
  become: true
  tasks:
    - name: Disable firewall
      ansible.builtin.systemd_service:
        name: firewalld
        state: stopped
