---
- name: Enable Ip_forward
  hosts: unstable
  become: true
  tasks:
    - name: Enabling forward
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: true
