global:
  domain: argo.lune.su

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    tls: true
    extraHosts:
      - name: argocd-alias.lune.su
        path: /

configs:
  params:
    server.insecure: "true"

service:
  type: ClusterIP
  ports:
    web:
      port: 80
      targetPort: 8080
