---
- name: Installing kubernetes
  ansible.builtin.import_playbook: ./install.yaml

- name: We install our cluster via kubeadm
  ansible.builtin.import_playbook: ./kubeadm.yaml

- name: Installing CNI Cilium
  ansible.builtin.import_playbook: ./cilium.yaml

- name: Making the cluster single-node
  ansible.builtin.import_playbook: ./single-node.yaml

- name: Creating space
  ansible.builtin.import_playbook: ./space/import.yaml
  tags: test

- name: Creating storage
  ansible.builtin.import_playbook: ./storage/import.yaml
