---
- name: Installing kubernetes
  ansible.builtin.import_playbook: ./install.yaml

- name: Initializing master-node Kubernetes
  ansible.builtin.import_playbook: ./kubeadm-init.yaml

- name: Installing CNI Cilium
  ansible.builtin.import_playbook: ./cilium.yaml

- name: Initializing worker-node Kubernetes
  ansible.builtin.import_playbook: ./kubeadm-join.yaml

- name: Creating space
  ansible.builtin.import_playbook: ./space/import.yaml

- name: Creating storage
  ansible.builtin.import_playbook: ./storage/import.yaml

- name: Installing gateway api
  ansible.builtin.import_playbook: ./gateway/install.yaml
