- name: Installing full Kubernetes with Flannel
  hosts: unstable
  become: true

  tasks:
    - name: Install Kubernetes repo
      ansible.builtin.copy:
        src: ./kubernetes.repo.j2
        dest: /etc/yum.repos.d/kubernetes.repo
        follow: true
        remote_src: false

    - name: Install kubelet, kubeadm, kubectl
      ansible.builtin.dnf:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: latest

    - name: Start and enable kubelet
      ansible.builtin.systemd_service:
        name: kubelet
        state: started
        enabled: true


