---
- name: Setting up kubeadm // infra/ansible/playbook/kubernetes/default/kubeadm.yaml
  hosts:
    - dev
    - test
    - prod
  become: true
  tasks:
    - name: Initialize Kubernetes cluster
      ansible.builtin.command: kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket=unix:///var/run/crio/crio.sock
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create .kube directory for root
      ansible.builtin.file:
        path: /root/.kube
        state: directory
        owner: user
        group: user
        mode: "0755"
        recurse: true

    - name: Copy kubeconfig to root
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        owner: user
        group: user
        mode: "0644"
        remote_src: true
