---
- name: Create docker-registry and tls secrets
  hosts: dev
  become: true

  vars:
    docker_registry_username: "{{ docker_login }}"
    docker_registry_password: "{{ docker_password }}"
    namespaces:
      - nm-argo
      - nm-gitlab
      - nm-elk # PV error
      - nm-monitoring
      - nm-nexus # PV error
      - nm-traefik
      # - nm-vault # PV error

  vars_files:
    - ../../secrets/secrets.yaml

  tasks:
    - name: Create docker-registry secret in each namespace
      ansible.builtin.shell: |
        kubectl create secret docker-registry docker-secrets \
          --docker-username={{ docker_login }} \
          --docker-password={{ docker_password }} \
          -n {{ item }} --dry-run=client -o yaml | kubectl apply -f -
      loop: "{{ namespaces }}"
      loop_control:
        label: "{{ item }}"

    - name: Copy TLS/SSL certificates
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/user/
        mode: "0600"
      loop:
        - ../../secrets/cert.pem
        - ../../secrets/privkey.pem

    - name: Create tls secret
      ansible.builtin.shell: |
        kubectl create secret tls tls-key \
          --cert=/home/user/cert.pem \
          --key=/home/user/privkey.pem \
          -n nm-gitlab --dry-run=client -o yaml | kubectl apply -f -

    - name: Delete copied TLS/SSL certificates
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /home/user/cert.pem
        - /home/user/privkey.pem
