---
- name: Single node cluster setup // infra/ansible/playbook/kubernetes/default/single-node.yaml
  hosts:
    - dev
    - test
    - prod
  become: true

  tasks:
    - name: We check that the control plane is not installed
      ansible.builtin.command: kubeclt cluster-info
      changed_when: false
      ignore_errors: true
      register: check_cluster

    - name: Untaint control plane nodes
      ansible.builtin.command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
      changed_when: false
      when: check_cluster.rc != 0
