---
- name: Create docker secret in all namespaces
  hosts: dev
  become: true
  gather_facts: false
  tasks:
    - name: Get all namespaces
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
      register: nm_list

    - name: Create docker secret in each namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: docker-secrets
            namespace: "{{ item.metadata.name }}"
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ lookup('file', './auth.json') | b64encode }}"
      loop: "{{ nm_list.resources }}"
