---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-alloy-lune-su
  namespace: nm-alloy
spec:
  parentRefs:
    - name: alloy-traefik-gateway
      namespace: nm-traefik
      sectionName: websecure
  hostnames:
    - "alloy.lune.su"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: alloy-server
          port: 12345
          kind: Service
