apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-nexus-lune-su
  namespace: nm-nexus
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: nm-traefik
      sectionName: websecure
  hostnames:
    - "nexus.lune.su"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nexus-nexus-repository-manager
          port: 8081
          kind: Service
