apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argo-lune-su
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argo.lune.su`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
  tls:
    certResolver: myresolver
