apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch
  labels:
    helm.sh/chart: eck-elasticsearch-0.14.1
    app.kubernetes.io/name: eck-elasticsearch
    app.kubernetes.io/instance: es-kb-quickstart
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "elasticsearch.lune.su"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elasticsearch-es-http
                port:
                  number: 9200

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: es-kb-quickstart-eck-kibana
  labels:
    helm.sh/chart: eck-kibana-0.14.1
    app.kubernetes.io/name: eck-kibana
    app.kubernetes.io/instance: es-kb-quickstart
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "kibana.lune.su"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: es-kb-quickstart-eck-kibana-kb-http
                port:
                  number: 5601
